services:
  fastapi-project-template-alembic:
    build:
      context: ..
      dockerfile: Containerfile
    image: fastapi-project-template
    container_name: fastapi-project-template-alembic

#    volumes:
#      - ../..:/workspaces:cached

    command: [ "python3", "-m", "alembic", "upgrade", "head" ]
    environment:
      DB_DSN: "postgresql+asyncpg://${POSTGRES_USER:-dev}:${POSTGRES_PASSWORD:-dev}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-fastapi-project-template}"
      LOGGING_LEVEL: "${LOGGING_LEVEL:-DEBUG}"
    network_mode: service:db
    depends_on:
      - db

  fastapi-project-template:
    build:
      context: ..
      dockerfile: Containerfile
    image: fastapi-project-template
    container_name: fastapi-project-template

#    volumes:
#      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    depends_on:
      - db

  db:
    image: postgres:18-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-fastapi-project-template}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-dev}"
      POSTGRES_USER: "${POSTGRES_USER:-dev}"
    restart: unless-stopped

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
