{{- if .Values.react.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-project-template.fullname" . }}-react
  labels:
    {{- include "fastapi-project-template.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fastapi-project-template.react.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fastapi-project-template.react.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: react
          image: "{{ .Values.react.image.repository }}:{{ .Values.react.image.tag }}"
          imagePullPolicy: {{ .Values.react.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.react.resources | nindent 12 }}
{{- end }}
